baseURL = ""
languageCode = "en-us"
title = "Nikkei Student Union"
theme = "hugo-nsu-theme"
googleAnalytics = "UA-XXXXXXXX-Y"

[params]
    # head theme color
    theme_color = "#CF1138"

    # head description
    # This is what appears on the preview when posting this site on Facebook for example
    description = ""

    # head photo, place this in the static/img folder
    # This is what appears on the preview when posting this site on Facebook for example
    description_photo = "preview.jpg"

    # favicon image (512x512px), place this in the static/img folder
    favicon = "favicon.png"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    # Email
    email = "nsuchapman@chapman.edu"

    # Facebook url
    facebook = "https://www.facebook.com/chapman.nsu"

    # Twitter username
    twitter = "chapmannsu"

    # LinkedIn URL
    # linkedin = ""

    # Medium username
    # medium = "asdf"

[params.nav]
    enable = true

[params.hero]
    enable = true

    # Place this image in the static/img folder
    hero = "hero.jpg"

    title = "Nikkei Student Union"
    subtitle = "Chapman University"
    slogan = "Promoting and celebrating Japanese-American Culture"
    call_to_action = "JOIN US"

[params.why_us]
    enable = true
    title = "Why come to us"

[params.events]
    enable = true
    title = "Upcoming Events"
    subtitle = "Selected Works"

[params.newsletter]
    enable = true
    title = "Newsletter Spiel"
    subtitle = "Newsletter subtitle"
    call_to_action = "JOIN US"

[params.footer]
    enable = true